server:
   port: 9090
   
spring:
   application:
      name: Merchants-Application
   datasource:
      username: root
      password: Perkinelmer123
      url: jdbc:mysql://127.0.0.1:3306/passbook
      
   kafka:
      bootstrap-servers: linux-dev.mshome.net:9092
      consumer:
         group-id: merchants-passtemplate-kafka-groupp
         
logging:
   level:
      root: debug