spring:
   application:
      name: Merchants-Application
   server:
      port: 9090
   datasource:
      username: root
      password: Perkinelmer123
      url: jdbc:mysql://127.0.0.1:3306/passbook